<?xml version="1.0"?>
<robot name="shl-1" xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:property name="WHEEL_RADIUS" value="0.0825"/>
  <xacro:property name="WHEEL_WIDTH"  value="0.07"/>
  <xacro:property name="WHEELBASE_L"  value="0.54"/>
  <xacro:property name="TRACK_W"      value="0.53"/>
  <xacro:property name="WHEEL_Z"      value="0.0"/>

  <xacro:property name="x_f" value="${WHEELBASE_L/2.0}"/>
  <xacro:property name="x_m" value="0.0"/>
  <xacro:property name="x_r" value="${-WHEELBASE_L/2.0}"/>
  <xacro:property name="y_l" value="${TRACK_W/2.0}"/>
  <xacro:property name="y_r" value="${-TRACK_W/2.0}"/>

  <material name="black"><color rgba="0 0 0 1" /></material>
  <material name="light_black"><color rgba="0.1 0.1 0.1 1" /></material>

  <xacro:macro name="sd_wheel" params="name parent x y z">
    <link name="${name}_horizontal_arm">
      <visual>
        <xacro:if value="${y > 0}"><origin xyz="0 0.05 0"/></xacro:if>
        <xacro:unless value="${y > 0}"><origin xyz="0 -0.05 0"/></xacro:unless>
        <geometry><box size="0.04 0.1 0.04"/></geometry>
        <material name="light_black"/>
      </visual>
    </link>
    <joint name="${name}_horizontal_arm_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}_horizontal_arm"/>
      <xacro:if value="${y > 0}"><origin xyz="${x} 0.169 ${z}" rpy="0 0 0"/></xacro:if>
      <xacro:unless value="${y > 0}"><origin xyz="${x} -0.169 ${z}" rpy="0 0 0"/></xacro:unless>
    </joint>
    <link name="${name}_vertical_upright">
      <visual>
        <origin xyz="0 0 -0.125"/>
        <geometry><box size="0.04 0.04 0.25"/></geometry>
        <material name="black"/>
      </visual>
    </link>
    <joint name="${name}_steer_joint" type="revolute">
      <parent link="${name}_horizontal_arm"/>
      <child  link="${name}_vertical_upright"/>
      <xacro:if value="${y > 0}"><origin xyz="0 0.1 0" rpy="0 0 0"/></xacro:if>
      <xacro:unless value="${y > 0}"><origin xyz="0 -0.1 0" rpy="0 0 0"/></xacro:unless>
      <axis xyz="0 0 1"/>
      <limit lower="-0.785398" upper="0.785398" effort="20" velocity="6.28"/>
    </joint>
    <link name="${name}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="-1.57079632679 0 0"/>
        <geometry>
          <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}"/>
        </geometry>
        <material name="black"/>
      </visual>
    </link>
    <joint name="${name}_drive_joint" type="continuous">
      <parent link="${name}_vertical_upright"/>
      <child  link="${name}_wheel"/>
      <xacro:if value="${y > 0}"><origin xyz="0 0.0575 -0.25" rpy="0 0 0"/></xacro:if>
      <xacro:unless value="${y > 0}"><origin xyz="0 -0.0575 -0.25" rpy="0 0 0"/></xacro:unless>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry><box size="0.54 0.338 0.202"/></geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/><material name="black"/>
    </visual>
  </link>

  <link name="base_footprint"></link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.3325" rpy="0 0 0"/>
  </joint>

  <link name="armario">
     <visual><geometry><box size="0.715 0.49 0.655"/></geometry><material name="black"/></visual>
  </link>
  <joint name="armario_link_joint" type="fixed">
    <parent link="base_link"/>
    <child link="armario"/>
    <origin rpy="0 0 0" xyz="0.002 0 0.5025 "/>
  </joint>

  <link name="base_battery">
    <visual>
      <geometry><mesh filename="package://rse_shl1_description/meshes/bases/trapezoid_battery.stl"/></geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry><mesh filename="package://rse_shl1_description/meshes/bases/trapezoid_battery.stl"/></geometry>
    </collision>
  </link>

  <joint name="base_battery_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_battery"/>
    <origin xyz="-0.003 0 -0.15"/>
  </joint>

  <xacro:sd_wheel name="fl" parent="base_link" x="${x_f}" y="${y_l}" z="${WHEEL_Z}"/>
  <xacro:sd_wheel name="fr" parent="base_link" x="${x_f}" y="${y_r}" z="${WHEEL_Z}"/>
  <xacro:sd_wheel name="ml" parent="base_link" x="${x_m}" y="${y_l}" z="${WHEEL_Z}"/>
  <xacro:sd_wheel name="mr" parent="base_link" x="${x_m}" y="${y_r}" z="${WHEEL_Z}"/>
  <xacro:sd_wheel name="rl" parent="base_link" x="${x_r}" y="${y_l}" z="${WHEEL_Z}"/>
  <xacro:sd_wheel name="rr" parent="base_link" x="${x_r}" y="${y_r}" z="${WHEEL_Z}"/>

</robot>